BO_SHOP/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Runtime.Remoting.Messaging;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BO_SHOP.Models;
using DAL_SHOP.Models;
using DAL_SHOP.UtilityModels;

namespace BO_SHOP.Controllers
{
    public class ProductsController : Controller
    {
        private ContextDB db = new ContextDB();
        static productspaging productpg = new productspaging();
        // GET: Products
        public ActionResult Listproduct(int pageNumber = 1, int? pageSize = 15, string keyword = "", int? trending = null, int? isview = null)
        {
            productpg.view = isview;
            productpg.trending = trending;
            productpg.pageCurrent = pageNumber;
            List<ProductRow> products = new List<ProductRow>();
            using (SqlConnection conn = new SqlConnection(ContextDB_ULT.connectionString))
            {
                conn.Open();
                using (var command = new SqlCommand("GetPagedProducts", conn))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.Add(new SqlParameter("@PageNumber", pageNumber));
                    command.Parameters.Add(new SqlParameter("@PageSize", pageSize));
                    command.Parameters.Add(new SqlParameter("@Trending", trending));
                    command.Parameters.Add(new SqlParameter("@Keyword", keyword));
                    command.Parameters.Add(new SqlParameter("@IsView", isview));

                    //đăng nhập admin 
                    if (Session["user"]==null || ((User)Session["user"]).Role == 0)
                    {
                        command.Parameters.Add(new SqlParameter("@IsPublished", 2));
                    }
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            ProductRow pro = new ProductRow();
                            pro.Id = reader.GetInt32(0);
                            pro.CategoryName = reader.GetString(1);
                            pro.Shopname = reader.GetString(2);
                            pro.ProductName = reader.GetString(3);
                            if (!String.IsNullOrEmpty(reader["Slug"].ToString()))
                            {
                                pro.Slug = reader["Slug"].ToString();
                            }
                            else
                            {
                                pro.Slug = null;
                            }
                            if (!String.IsNullOrEmpty(reader["Views"].ToString()))
                            {
                                pro.Views = int.Parse(reader["Views"].ToString());
                            }
                            else
                            {
                                pro.Views = 0;
                            }
                            if (!String.IsNullOrEmpty(reader["IsPublished"].ToString()))
                            {
                                pro.IsPublished = int.Parse(reader["IsPublished"].ToString());
                            }
                            else
                            {
                                pro.IsPublished = 0;
                            }

                            if (!String.IsNullOrEmpty(reader["ProductDetail"].ToString()))
                            {
                                pro.ProductDetail = reader["ProductDetail"].ToString();
                            }
                            else
                            {
                                pro.ProductDetail = null;
                            }
                            pro.Price = decimal.Parse(reader["Price"].ToString());
                            pro.Trending = bool.Parse(reader["Trending"].ToString());
                            dynamic CreatedAt = reader["CreatedAt"].ToString();
                            if (!String.IsNullOrEmpty(CreatedAt))
                            {
                                pro.CreatedAt = DateTime.Parse(reader["CreatedAt"].ToString());
                            }
                            else
                            {
                                pro.CreatedAt = null;
                            }
                            dynamic dayUpdate = reader["UpdateAt"].ToString();
                            if (!String.IsNullOrEmpty(dayUpdate))
                            {
                                pro.UpdateAt = DateTime.Parse(reader["UpdateAt"].ToString());
                            }
                            else
                            {
                                pro.UpdateAt = null;
                            }
                            dynamic dayDelete = reader["DeletedAt"].ToString();

                            if (!String.IsNullOrEmpty(dayDelete))
                            {
                                pro.DeletedAt = DateTime.Parse(reader["DeletedAt"].ToString());
                            }
                            else
                            {
                                pro.DeletedAt = null;
                            }
                            products.Add(pro);
                        }
                        reader.NextResult();
                        while (reader.Read())
                        {
                            productpg.total = reader.GetInt32(0);
                        }
                    }
                }
                for(int i = 0; i < products.Count(); i++)
                {
                    List<Media> medias = new List<Media>();
                    using (var command = new SqlCommand("MediasShowById", conn))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.Parameters.Add(new SqlParameter("@id", products[i].Id));
                        using (var reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                Media media = new Media();
                                media.Id = reader.GetInt32(0);
                                media.MediasName = reader.GetString(1);
                                media.PathLink= reader.GetString(2);
                                media.MediaType = int.Parse(reader["MediaType"].ToString());
                                media.ProductId = reader.GetInt32(4);
                                dynamic CreatedAt = reader["CreatedAt"].ToString();
                                if (!String.IsNullOrEmpty(CreatedAt))
                                {
                                    media.CreatedAt = DateTime.Parse(reader["CreatedAt"].ToString());
                                }
                                else
                                {
                                    media.CreatedAt = null;
                                }
                                dynamic dayUpdate = reader["UpdateAt"].ToString();
                                if (!String.IsNullOrEmpty(dayUpdate))
                                {
                                    media.UpdateAt = DateTime.Parse(reader["UpdateAt"].ToString());
                                }
                                else
                                {
                                    media.UpdateAt = null;
                                }
                                dynamic dayDelete = reader["DeletedAt"].ToString();

                                if (!String.IsNullOrEmpty(dayDelete))
                                {
                                    media.DeletedAt = DateTime.Parse(reader["DeletedAt"].ToString());
                                }
                                else
                                {
                                    media.DeletedAt = null;
                                }
                                medias.Add(media);
                            }
                        }
                    }
                    products[i].medias = medias;
                }
            }
            productpg.ds_p = products;
            return View(productpg);
        }

       
        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categorys, "Id", "CategoryName");
            ViewBag.Shopid = new SelectList(db.Shops, "Id", "Shopname");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(FormCollection f)
        {
                Media m = new Media();
            Product p = new Product();
            p.Id = db.Products.Max(u => u.Id) + 1;
            p.Productname = Request["Productname"].ToString();
            p.Slug = Request["Slug"].ToString();
            p.CategoryId = int.Parse(Request["CategoryId"].ToString());
            p.Shopid = int.Parse(Request["Shopid"].ToString());
            p.ProductDetail = Request["ProductDetail"].ToString();
            if (String.IsNullOrEmpty(Request["Price"].ToString()))
            {
                ViewBag.ErrorMessage = "Price không được để trống";
                return View("Create");
            }
            p.Price = decimal.Parse(Request["Price"].ToString());
            var tam = Request["Trending"];
            if (tam!=null)
            {
                p.Trending = true;
            }
            else
            {
                p.Trending= false;

BO_SHOP/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text.RegularExpressions;
using System.Text;
using System.Web;
using System.Web.Mvc;
using DAL_SHOP.Models;

namespace BO_SHOP.Controllers
{
    public class UsersController : Controller
    {
        // GET: Client
        private ContextDB db = new ContextDB();

        // GET: Users
        public ActionResult MyProfile()
        {
            if (Session["user"] == null)
            {
                return Content("<h1>Bạn cần đăng nhập trước khi thực hiện các tác vụ này!!!</h1><a href='/Login/Login'>Đăng nhập</a>");
            }
            User u = (User)Session["user"];
            return View(u);
        }
        [HttpPost]
        public ActionResult MyProfilePost()
        {
            int Id = ((User)Session["user"]).Id;
            var u = db.Users.FirstOrDefault(_u => _u.Id == Id);
            string name = Request["username"];
            if (name == null)
            {
                ViewBag.ErrorUserNameVal = "Username không được để trống";
                return View("MyProfile",u);
            }
            if (u.Username != name)
            {
                if (db.Users.FirstOrDefault(x => x.Username == name) == null)
                {
                    u.Username = name;
                }
                else
                {
                    ViewBag.ErrorUserNameVal = "Username dã tồn tại";
                    return View("MyProfile",u);
                }
            }

            string pattern = "[^a-zA-Z0-9]"; // biểu thức chính quy: không phải ký tự a-z, A-Z, 0-9
            bool containsSpecialChars = Regex.IsMatch(u.Username, pattern); // kiểm tra chuỗi có chứa ký tự đặc biệt hay không
            if (containsSpecialChars)
            {
                ViewBag.ErrorUserNameVal = "Chuỗi không được chứa ký tự đặc biệt";
                return View("MyProfile", u);
            }
            u.UpdatedAt = DateTime.Now;

            string password_new = Request["password_new"];
            if (password_new != null)
            {
                string password_new_comfirm = Request["password_new_comfirm"];
                string passwordPattern = @"^(?=.*[A-Z])(?=.*[0-9])(?=.*[^\w\s]).{8,20}$";
                if (!Regex.IsMatch(password_new, passwordPattern))
                {
                    ViewBag.Error = "Password phải từ 8-20 kí tự bao gồm ít nhất 1 kí tự số, 1 kí tự viết hoa và 1 kí tự đặc biệt";
                    return View("MyProfile", u);
                }
                if (string.IsNullOrEmpty(password_new_comfirm))
                {
                    ViewBag.Error = "Confirm password không được để trống";
                    return View("MyProfile", u);
                }
                SHA256 sha = SHA256.Create();
                if (password_new != password_new_comfirm)
                {
                    ViewBag.Error = "password và confirm passowrd không khớp";
                    return View("MyProfile", u);
                }
                //byte[] rs = sha.ComputeHash(Encoding.UTF8.GetBytes(password_new));
                //password_new = BitConverter.ToString(rs).Replace("-", string.Empty);
                u.Password = password_new;
            }

            db.SaveChanges();
            ViewBag.Success = "Sửa thông tin thành công";
            return View("Listuser");
        }
    }
}

BO_SHOP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/Login/base.css">
    <link rel="stylesheet" href="~/Content/Login/main.css">
</head>
<body>
    <!-- Header với Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav w-100">

                @*chưa đăng nhập*@ 
                @if (Session["user"] == null)
                {
                    <li class="nav-item active">
                        @Html.ActionLink("Home", "Listproduct", "Products", null, new { @class = "nav-link" })
                    </li>
                }
                @*đăng nhập với tư cách user*@ 
                else if (Session["user"] != null && ((DAL_SHOP.Models.User)Session["user"]).Role == 0)
                {
                    <li class="nav-item">
                        @Html.ActionLink("Product", "Listproduct", "Products", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("My reviews", "Index", "Home", null, new { @class = "nav-link" })

                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("My wishlists ", "Index", "Home", null, new { @class = "nav-link" })
                    </li>
                }
                @*đăng nhập với tư cách admin*@
                else
                {

                    <li class="nav-item">
                        @Html.ActionLink("List User", "Listuser", "Admin", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("List Shop", "Listshop", "Admin", null, new { @class = "nav-link" })

                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("List Review", "Index", "Home", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("List Product", "Listproduct", "Products", null, new { @class = "nav-link" })
                    </li>
                }
            </ul>
            @*chưa đăng nhập*@ 
            @if (Session["user"] == null)
            {
                <ul class="navbar-nav ">
                    <li class="nav-item">
                        @Html.ActionLink("Login", "Login", "Login", null, new { @class = "nav-link float-lg-end" })
                    </li>
                    <li class="navbar-nav ">
                        @Html.ActionLink("Register", "Register", "Login", null, new { @class = "nav-link float-lg-end" })

                    </li>

                </ul>
            }
            @*đã đăng nhập và hiển thị tên người đăng nhập*@ 
            else
            {
                string name = ((DAL_SHOP.Models.User)Session["user"]).Username;
                <ul class="navbar-nav ">
                    <li class="dropdown ">
                        <a href="@Url.Action(null)" class="nav-link float-right dropdown-toggle" data-toggle="dropdown">@name</a>

                        <ul style="left: -76px;" class="dropdown-menu">
                            <li>@Html.ActionLink("My Profile", "MyProfile", "Users", null, new { @class = "dropdown-item" })</li>
                            <li>@Html.ActionLink("Logout", "Logout", "Login", null, new { @class = "dropdown-item" })</li>
                        </ul>
                    </li>
                </ul>
            }
        </div>
    </nav>
    <div style="max-width: none" class="container  body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>